### ISSUE TITLE
Ensure documentation is up to date before completion of 0.1.0

### ISSUE THREAD

**Issue by JrTheDragon01** [Dustpancake/Asteroid#43]
As a final step before completing the 0.1.0 milestone it'd be good to ensure all relevant functions are covered by documentation and to possibly put documentation in the github wiki page for this. Related to #32 as afaik that's not fully sorted

**Comment by Dustpancake** [comment]
Well, whilst  #32 is still an issue this is going to be tricky. I haven't had the willpower to mess about with JSDoc in a while -- if you want to look into this, please be my guest :)

**Comment by JrTheDragon01** [comment]
I would look into it if only JSDoc worked at all on my raspi :/ will try again to get it working at some point soon

**Comment by Dustpancake** [comment]
No longer worrying about sphinx; stubbed for now.
